name: Keep Streamlit Alive

on:
  schedule:
    # 毎日2時間おきに実行 (UTC時間)
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Streamlit App
        run: |
          curl -sS -k --max-redirs 10 "https://8zzzhcibve6lr2r2k4pvfj.streamlit.app" || true
          curl -sS -k --max-redirs 10 "https://djks33sfzskwjzeam4mbcr.streamlit.app" || true
          
