name: Keep Streamlit Alive via Auto Commit

on:
  schedule:
    # 6時間おきに自動で空コミットを送信
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dummy Commit to Trigger Rebuild
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Chore: Auto keep-alive rebuild"
          git push
